spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 095ef5f1f9e96f6e8d09611b03869227
          google:
            clientId: 326541986365-vhad7c5815a046ikq494huarem5sk98m.apps.googleusercontent.com
            clientSecret: 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

