spring:
  devtools:
    livereload:
      # livereload 서버 켜기
      enabled: true
    remote:
      restart:
        # 원격 재시작 활성화
        enabled: true
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/gram__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldj
    password: lldj123414
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 095ef5f1f9e96f6e8d09611b03869227
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        google:
          clientId: <your-google-client-id>
          clientSecret: <your-google-client-secret>
          scope:
            - email
            - profile
          provider:
            google:
              authorizeUrl: https://accounts.google.com/o/oauth2/auth
              tokenUrl: https://accounts.google.com/o/oauth2/token
              userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
              userNameAttributeName: sub
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.ll.gramgram_ai: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
